install.packages("rstatix")
install.packages("gplots")
install.packages("car")
install.packages("ggpubr")
install.packages("VCA")
install.packages("ez")
install.packages("PMCMRplus")

library(rstatix)
library(dplyr)
library(gplots)
library(car)
library(ggpubr)
library(vca)
library(ez)
library(PMCMRplus)